import logo from '../assets/images/logo.png'
import frame from '../assets/images/Arts/Frame.png'
import rectangle1 from '../assets/images/Arts/Rectangle.png'
import rectangle2 from '../assets/images/Arts/Rectangle2.png'
import rectangle3 from '../assets/images/Arts/Rectangle3.png'
import rectangle4 from '../assets/images/Arts/Rectangle4.png'
import rectangle5 from '../assets/images/Arts/Rectangle5.png'
import rectangle6 from '../assets/images/Arts/Rectangle6.png'
import rectangle7 from '../assets/images/Arts/Rectangle7.png'
import rectangle8 from '../assets/images/Arts/Rectangle8.png'
import add from '../assets/images/icons/Add.png'
import arrowRight from '../assets/images/icons/ArrowRight.png'
import check from '../assets/images/icons/Check.png'
import directionDown from '../assets/images/icons/DirectionDown.png'
import directionLeft from '../assets/images/icons/DirectionLeft.png'
import directionRight from '../assets/images/icons/DirectionRight.png'
import directionUp from '../assets/images/icons/DirectionUp.png'
import directionUpDown from '../assets/images/icons/DirectionUpdown.png'
import minus from '../assets/images/icons/Minus.png'
import person from '../assets/images/icons/Person.png'
import redEye from '../assets/images/icons/Removeredeye.png'
import search from '../assets/images/icons/Search.png'
import shippingTruck from '../assets/images/icons/ShippingTruck.png'
import stateAdded from '../assets/images/icons/StateAdded.png'
import stateDefault from '../assets/images/icons/StateDefault.png'
import stateHover from '../assets/images/icons/StateHover.png'
import typeAdded from '../assets/images/icons/TypeAdd.png'
import typeHeart from '../assets/images/icons/TypeHeart.png'
import typeDefault from '../assets/images/icons/TypeDefault.png'
import typeError from '../assets/images/icons/TypeError.png'
import typeInfo from '../assets/images/icons/TypeInfo.png'
import typeOutline from '../assets/images/icons/TypeOutline.png'
import typeSolid from '../assets/images/icons/TypeSolid.png'
import typeWarning from '../assets/images/icons/TypeWarning.png'
import typeX from '../assets/images/icons/X.png'
import EllipseBig from '../assets/images/Profiles/Ellipse1Big.png'
import Ellipse6 from '../assets/images/Profiles/Ellipse6.png'
import Ellipse4 from '../assets/images/Profiles/Ellipse4.png'
import Ellipse5 from '../assets/images/Profiles/Ellipse5.png'
import Ellipse7 from '../assets/images/Profiles/Ellipse7.png'
import EllipseLogo from '../assets/images/Profiles/EllipseLogo.png'
import vector from '../assets/images/vectors/Vector.png'
import vector2 from '../assets/images/vectors/Vector2.png'
import vector3 from '../assets/images/vectors/Vector3.png'
import vector4 from '../assets/images/vectors/Vector4.png'
import rightArrow from '../assets/images/icons/ArrowRight-violet.png'
import BG1 from '../assets/images/Arts/BG1.png'
import BG2 from '../assets/images/Arts/BG2.png'
import BG3 from '../assets/images/Arts/BG3.png'
import BG4 from '../assets/images/Arts/BG4.png'
import BG11 from '../assets/images/Arts/BG11.png'
import BG12 from '../assets/images/Arts/BG12.png'
import BG13 from '../assets/images/Arts/BG13.png'
import BG21 from '../assets/images/Arts/BG21.png'
import BG22 from '../assets/images/Arts/BG22.png'
import BG23 from '../assets/images/Arts/BG23.png'
import BG31 from '../assets/images/Arts/BG31.png'
import BG32 from '../assets/images/Arts/BG32.png'
import BG33 from '../assets/images/Arts/BG33.png'
import BG41 from '../assets/images/Arts/BG41.png'
import BG42 from '../assets/images/Arts/BG42.png'
import BG43 from '../assets/images/Arts/BG43.png'
import BGI1 from '../assets/images/Profiles/BGI1.png'
import BGI2 from '../assets/images/Profiles/BGI2.png'
import BGI3 from '../assets/images/Profiles/BGI3.png'
import BGI4 from '../assets/images/Profiles/BGI4.png'
import Shop1 from '../assets/images/vectors/Shop1.png'
import Shop2 from '../assets/images/vectors/Shop2.png'
import Shop3 from '../assets/images/vectors/Shop3.png'
import Shopb1 from '../assets/images/vectors/Shopb1.png'
import Shopb2 from '../assets/images/vectors/Shopb2.png'
import Shopb3 from '../assets/images/vectors/Shopb3.png'
import lorry from '../assets/images/icons/Lorry.png'


export default  {
    logo,
    frame,
    rectangle1,
    rectangle2,
    rectangle3,
    rectangle4,
    add,arrowRight,check,directionDown,directionLeft,directionRight,directionUp,directionUpDown,minus,person,redEye,
    search,shippingTruck,stateAdded,stateDefault,stateHover,typeAdded,typeDefault,typeError,typeInfo,typeOutline,typeSolid,typeWarning,typeX,EllipseBig,
    Ellipse6,EllipseLogo,vector,vector2,vector3,vector4,Ellipse4,Ellipse5,Ellipse7,
    rectangle5,rectangle6,rectangle7,rectangle8,rightArrow,typeHeart,
    BG1,BG2,BG3,BG4,
    BG11,BG12,BG13,BG21,BG22,BG23,BG31,BG32,BG33,BG41,BG42,BG43,BGI1,BGI2,BGI3,BGI4,
    Shop1,Shop2,Shop3,Shopb1,Shopb2,Shopb3,lorry
}